// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_dashboard_ from "./routes/[dashboard].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $api_events_dashboard_ from "./routes/api/events/[dashboard].ts";
import * as $index from "./routes/index.tsx";
import * as $ClockIsland from "./islands/ClockIsland.tsx";
import * as $MarkdownIsland from "./islands/MarkdownIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[dashboard].tsx": $_dashboard_,
    "./routes/_404.tsx": $_404,
    "./routes/api/events/[dashboard].ts": $api_events_dashboard_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ClockIsland.tsx": $ClockIsland,
    "./islands/MarkdownIsland.tsx": $MarkdownIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
